# Generated by Django 4.1.5 on 2023-01-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimulationEtudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidats',
            fields=[
                ('etudiant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SimulationEtudiant.etudiant')),
                ('voix', models.IntegerField()),
            ],
            bases=('SimulationEtudiant.etudiant',),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
